argocd:
  prod:
    api_url: "https://localhost:8080"
    username: "admin"
    password: "${ARGOCD_PROD_PASS}"
tekton:
  prod:
    api_url: "https://172.29.36.235:8443"
    token: "${KUBE_PROD_TOKEN}"